server:
  port: 8887
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8443/eureka
spring:
  application:
    name: providers
  jmx:
    enabled: false
    default-domain: provider