server:
  port: 8886
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8443/eureka
spring:
  application:
    name: consumers
  jmx:
#    enabled: false
    default-domain: consumer

